### ISSUE TITLE
Beastmen 2.4

### ISSUE THREAD

**Issue by cartag** [sprutton1/AgeOfFantasyBattlescribe#11]
I've already completed the file, just need to be able to upload it. I've been a data dev for 40k, AoS, and Gaslands. I'm used to working with BS.

**Comment by Darguth** [comment]
@cartag I grabbed it off OPR, did some editing and put it up for review. It's been added now. @sprutton1 would have to make you a contributor if you want to assist long-term. Alternatively you could fork the repo, work in your own, then put up PRs to merge back to this master one as well. That's what I did originally.
