### ISSUE TITLE
Suggestion: Force Entry for Beasts

### ISSUE THREAD

**Issue by cartag** [sprutton1/AgeOfFantasyBattlescribe#12]
In working on the Beastmen file, I noticed there are some units that don't fit cleanly into the options we have. In addition to Infantry and Cavalry, might I suggest "Beast" as a category to cover Warhounds, Boars, Blood Hounds, and the like.

**Comment by Darguth** [comment]
@cartag I'd personally just classify these as Cavalry. They generally serve a similar role as light cav in lists (they're basically the lightest/cheapest form of cavalry). Additionally, most army lists are going to have 0-1 entries in this category so it just seems a bit extraneous.

**Comment by Darguth** [comment]
@cartag just put up a PR to add this. I haven't recategorized anything, but the category now exists. After doing a few other armies like Ratmen and whatnot I came to agree with you that this category would be handy afterall. You were right! :)
