### ISSUE TITLE
Kingdom of Angels List

### ISSUE THREAD

**Issue by PerramUnderhill** [sprutton1/AgeOfFantasyBattlescribe#9]
I'm trying to teach myself this as I go. So far I've got Infantry and Battle Sisters working. :D

**Comment by PerramUnderhill** [comment]
First Github contribution... can't seem to assign myself as the readme suggests.

**Comment by Darguth** [comment]
@PerramUnderhill I'm looking to get back into actively developing this content. How's the KoA list going, anything I can help you with getting started?

**Comment by PerramUnderhill** [comment]
I nearly finished it. In fact I think it is completely finished. Just don't
know how to get it to you all.
